[package]
name = "strivedata"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-files = "0.6"

env_logger = "0.9"
log = "0.4"

r2d2 = "0.8"
r2d2_sqlite = "0.20"
rusqlite = "0.27"

serde = { version = "1", features = ["derive"] }
serde_json = "1"

tera = "1"
